### ISSUE TITLE
Add docker containers to docker hub.

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#119]
I've pinged docker customer support about it

**Comment by subdavis** [comment]
I'm not hopeful about our prospects.

I have https://hub.docker.com/u/kitwareviame already, but we can do something else if necessary.

We could also use the official kitware org, but since we have 3 images, we'd need to do `kitware/viame` and `kitware/viame-wokrer` or something like that.   I actually prefer this option.  There's a lot of traffic in the kitware org, and it makes the project look more reputable.  It also reduces the need to ping people every time someone new has to be added.
