### ISSUE TITLE
Box misalignment when buffering frames immediately after pressing play

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#127]
Very minor, seems to just be off by a frame see below (but for imagery off by a frame means completely different unlike video)

![buffer_offset](https://user-images.githubusercontent.com/2353972/82475516-985b9000-9a9a-11ea-9699-2cd7cc3e69ae.png)

**Comment by BryonLewis** [comment]
So the caching system is based on seconds.  It starts the loading spinner if it can't read the next 1 second of frames.  This is based on the FPS associated with the metadata for the folder.  I think that a lot of that data has it set to 30fps.  If you change the fps in the metadata to 1fps it will only show the  loading spinner on the currently waiting frame instead of trying to load 30 at a time.

In regards to being off by a frame, I will make sure that it emits a change to the frame when it goes backwards while waiting.

**Comment by aashish24** [comment]
@mattdawkins yeah it seems that the annotations are drawn at the wrong locations - and based on what you are saying is that imagery is off by a frame? Could be more than a frame I guess. Regardless it looks like a emit signal issue as @BryonLewis mentioned.
