### ISSUE TITLE
Seeking backward doesn't work, prefetching doesn't wait for frames to load.

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#13]
Pre-fetching only works when playing the video forward in time.  However, when doing an annotation, a user will want to find the beginning of the track, which can involve seeking backward.

* Find a fish you want to track
* grab the track head and drag backward to look for the fish's first appearance.

result: lots of waiting for an image to appear.

**Comment by BryonLewis** [comment]
I'm assuming this is referencing the ImageAnnotator, it is the one that has precaching of 10 frames ahead of the current position.

I don't know if this should be tacked onto this or a different issue, but the caching system and playing system has some flaws with slower connections.  
There is no waiting system for a specific set of frames to be loaded before playing.  This means that if you have a slower connection and try to play the image list it will just keep skipping ahead and trying to load new frames even if it can't load them in time for the specified frame rate.  It's main goal is to maintain frame rate and not to display the images.

**Comment by subdavis** [comment]
> It's main goal is to maintain frame rate and not to display the images.

Yeah I think that's a problem too.  We can break these into other issues if we end up working to fix them.

**Comment by BryonLewis** [comment]
Updated the caching system so it takes in some arguments for a number of seconds to cache.  Defaulting that right now to 8.  As you play through the scene the caching is a sliding window which continually updates so that should be okay. 

The caching now has a specifier for the allocation of time to the left(backwards) and right(forwards) of the current frame.  Specified as a number less than 1 it will use that number for the forward amount.  IE frontBackRatio=0.75 means that 75% of the specified cache time will look ahead while 25% will look backwards.

I've updated the playback so that if you encounter an image source in which `.complete` is falsey it will stop the playback and check the cache to make sure at least a user specified number of seconds (defaulted to 3 I believe) are available in their entirety before playing back again.  The same thing occurs if you attempt to hit play right after seeking.  It will wait for at least the minimum amount is available before resuming the playback.  This will displaying a loading spinner while waiting,  We can change this to a different icon, css animation or GIF if wanted.
![image](https://user-images.githubusercontent.com/61746913/78579619-3226f080-77ff-11ea-82a5-a2b646db2290.png)


Things left to do:

- [ ] I feel like the seeking and loading of a new single frame while seeking is taking too long.  Like it isn't properly killing the other requests for image data and is spending time waiting for other images before being able to seek.  I need to look into this a bit better

- [ ] Part of the above issue is that the caching shouldn't start at the minimum number (which is behind the current frame).  It would start at the currently seeked frame and then work it's way out in both directions from there.  Maybe even giving priority to the forward direction.

- [ ] `.complete` on an Image object has some caveats referenced in the MDN documentation.  Make sure these corner cases don't impact the caching system:[MDN docs for image.complete](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete)
