### ISSUE TITLE
Add Infrastructure for Electron

### ISSUE THREAD

**Issue by AlmightyYakob** [VIAME/VIAME-Web#159]
This would be the first step towards building the client for both the web and the desktop, which would involve adding the correct dependencies and determining the general structure of the app. 

Discussion document: https://docs.google.com/document/d/1cE7hDJia6Iz7QJM5nxpXLfbklrHPqIkrlbmMfU7Uds4

We'd also probably want to identify the calls to girder that would be replaced by node, and maybe start stubbing them out.

**Comment by subdavis** [comment]
I sort of think this is a typescript situation, where we look at what's already in `lib/api` and formalize the common parts with interfaces.  Then we can implement those interfaces with both a girder-backed and an electron-backed function.

As far as figuring out which one to use on application startup, I sort of had the idea that we could trivially do something like this:

`@/lib/api/base.ts`
```js
import { GirderApi } from './girder';
import { ElectronApi } from './electron';

let API;
if (process.env.WHATEVER) {
  API = new GirderApi();
} else {
  API = new ElectronApi();
}
export default API;
```

Then, because APIs both satisfy a common interface, you don't have to care about it in the rest of the app.  

I think we may run into issues where we have to build to a totally differerent ecmascript target version with special ignore rules when we build the electron client because the electron API works through inserting the `require` keyword onto `widow`, which is going to freak out all our linting/babel/whatever.

I'm sure there's a way to tell babel that `require` is OK and should be left alone if encountered in some files, but I don't know how typescript is going to feel about it.

**Comment by AlmightyYakob** [comment]
I like this idea, and hopefully it could address most of the issues we'd run into around building for the two different platforms.

> I think we may run into issues where we have to build to a totally differerent ecmascript target version with special ignore rules when we build the electron client because the electron API works through inserting the `require` keyword onto `widow`, which is going to freak out all our linting/babel/whatever.
> 
> I'm sure there's a way to tell babel that `require` is OK and should be left alone if encountered in some files, but I don't know how typescript is going to feel about it.

I'm not sure what you're referring to regarding needing `window.require`, but from [this](https://www.electronjs.org/blog/typescript#:~:text=The%20electron%20npm%20package%20now,you're%20writing%20vanilla%20JavaScript.) electron blog post, they don't seem to use it. I haven't work too much with Electron though, so I'm probably just missing something. Regardless I don't think it'll be too much of an obstacle to overcome.
