### ISSUE TITLE
Pixel-level annotation

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#163]
Using GeoJS polygon annotations to being with

**Comment by aashish24** [comment]
@aashish24 will provide a dataset to play with

**Comment by BryonLewis** [comment]
Need to create a mode switching mechanism so I can switch between Bounds and Polygon Modes.
Bounds mode allows you to edit the Rect where as polygon mode allows you to edit the polygon.
This switching of modes should also apply to visibility of rects and polygons for a track.

I like how geoJS does initial polygon drawing, but I need to make sure I don't disable it through the annotation layer by technically clicking on blank space.  Need some way to indicate that the polygon is DONE, and no more points need to be added.  Probably a right click should help with this when in new Polygon mode.

Not a huge fan of how polygons are edited, but It should work for now with the dragging of additional edges.  I'm looking currently into getting some other stuff to properly switch between rect and polygon.

**Comment by BryonLewis** [comment]
Putting together a TODO in here to list out things I need to to and update to get working properly:

- [ ] Create the Editing Mode interface, probably in the NavBar, when you're in edit mode you can choose Rectangle or Polygon
- [ ] Modify the styling so that the bounds for a Rect don't look like the polygon at the same time.  The bounds should be faded or dimmer if we are editing a polygon.
- [ ] Prevent clicking on other annotations when in creation mode for polygons, they need to have a special mode for themselves
- [ ] Subset to the above is to change the editing variable in `FrameData` from a boolean to string indicating the mode of editing, this can have multiple effects to clean up some complexity.
- [ ] Selection in the interface of a polygon or a rect and how it is done.  Do we select only polygons if they are available?
- [ ] Add in some sort of Text indicating what is going on in Polygon mode and how to add points and completion of adding points.

**Comment by BryonLewis** [comment]
Update to the above list:
Created interface for editing/visible.  Not finalized yet because use cases might include options.
So the first Tasks are done:
![image](https://user-images.githubusercontent.com/61746913/87689836-afdf8e00-c756-11ea-805a-f83211c69d20.png)
![image](https://user-images.githubusercontent.com/61746913/87689883-bc63e680-c756-11ea-8cce-4853b70238c4.png)
Added in line and point icons in there right now.  Will most likely remove them in the future.
Boundinb Box is thinner and more transparent when compared with polygon.
![image](https://user-images.githubusercontent.com/61746913/87689999-e4534a00-c756-11ea-916a-7984cc465724.png)
Still can edit polygon:
![image](https://user-images.githubusercontent.com/61746913/87690041-f03f0c00-c756-11ea-9da5-f6ef077d7366.png)

**Comment by BryonLewis** [comment]
Okay I have the above stuff finished future updates include:

- [ ] Need to look into geoJS and figure out deletion of points/selection of points
- [ ] Subset of above is to maybe use the new menu system for removing points
- [ ] Not sold on the help system I currently build I feel there is a better way to implement it.
- [ ] Possible move the `markerLayer` into the `EditLayer` as well
- [ ] Add in Line editor to create lines

**Comment by BryonLewis** [comment]
Working on removing points, I believe it has to be done manually through editing the source data and there is no system in place for doing it in GeoJS (At least I can't see anything in the documentation).  I need to be able to select a point of the polygon by clicking on it and then provide the ability to remove that point (by going through the polygon list and removing the index).  So I'm putting some infrastructure to support that.

Corner cases/Notes:
Once you get below 3 points you shouldn't be allowed to remove any more points, because it is no longer a polygon then.  
Also make sure you change the selected Index after it is removed if it is the last index in the order it needs to be updated or at least reset to -1 or some default non-existant value.
