### ISSUE TITLE
Create serializer for mevadata KPF file format

### ISSUE THREAD

**Issue by AlmightyYakob** [VIAME/VIAME-Web#174]
Link to download instructions: http://mevadata.org/resources/README-meva-kf1-data.txt

The main goal here would be to ensure that we can serialize this data into Viame-Web like any other file format (CSV or Track JSON), and allow for annotation as well as possibly export.

**Comment by subdavis** [comment]
Some additional details.

* KPF is a tricky data type assembled from any combination of 3 yaml files. 
* There's a python deserializer in a private package.  source code is here: https://gitlab.com/diva-mturk/stumpf-diva/-/blob/master/boiler/boiler/serialization/kpf.py but you can actually get that package on pypi https://pypi.org/project/diva-boiler/ and extract it to see the code.
* That package deserializes into similar-but-not-identical python dataclasses.  Those are defined here: https://gitlab.com/diva-mturk/stumpf-diva/-/blob/master/boiler/boiler/models.py
* MEVA data probably contains interpolated frames with no markings that specify that they're actually interpolated.  This is frustrating because it makes the files needlessly large and slow to parse.  It's sort of like if I asked you "Could you come up with a notation that means "All the numbers from 1 to 100"" and instead of `[1, 100]` you wrote all the numbers out.  `diva-boiler` has some features that can detect and remove interpolated (derived) data, but it doesn't work great, so we will probably just have to load the whole thing.

There are actually 2 options for how to do this task:

1. write new deserialization code to extract KPF directly to our internal schema
2. import `diva-boiler` as a dependency, then transform the boiler package's models into our models.

## Example Data

TODO, getting this now.

**Comment by subdavis** [comment]
@mattrix27 turns out you won't be able to use the code from boiler directly, and installing the command line really won't do much good.  I'll need your gitlab.com username to get you access to the code.

**Comment by subdavis** [comment]
You can use data from https://gitlab.kitware.com/meva/meva-data-repo/-/tree/master/annotation/DIVA-phase-2/MEVA/kitware/2018-03-15/15 or any of the related folders.  

I'm not quite sure where the video is, so I'll have to find it, but you shouldn't need video to get started.

Notice how in the boiler parser each file is optional.  I think that would be good to do here too.  All 3! combinations of files won't produce valid data, but as long as there's geometry, you should end up with a valid list of tracks.

Let me know if we should schedule a meeting to talk any of that.

**Comment by AlmightyYakob** [comment]
Had a discussion offline with @mattrix27, just wanted to clarify some things. This serializer will probably be used starting at the `GET /viame_detection` endpoint, where currently it has a single check if the detections are in `csv` format, and if so converts them to track JSON. We'd do something similar with KPF formatted files, probably checking against `yaml`. Once this has been done on the initial annotations, it'll be in track JSON format, so no further conversion will be needed.

To get back to KPF, we could either have a new endpoint, or just add a parameter that specifies type to the existing `GET /viame_detections/{folder}/export_detections`. Either way, this would follow a similar pattern to this endpoint:

https://github.com/VIAME/VIAME-Web/blob/e515d0e0d9a650c1e989ddefa614d847b478c764/server/viame_server/viame_detection.py#L114-L142

**Comment by subdavis** [comment]
> probably checking against yaml

Yeah that sounds good for now.

> To get back to KPF

Probably not worth doing KPF export yet.  Parsing is enough to meet the requirements.  A serializer will definitely be necessary, but I think the parser should be written first.
