### ISSUE TITLE
Allow changing of filenames

### ISSUE THREAD

**Issue by AlmightyYakob** [VIAME/VIAME-Web#20]
Pulled out from #18.

If uploading only 1 file, we should allow the renaming of files. This would necessitate an update to the `fileUploader` mixin in GWC.

**Comment by BryonLewis** [comment]
@subdavis  - I believe the end goal would be for Girder Web Components mixin to support the 'params' argument found in [./src/utils/Upload.js ](https://github.com/girder/girder_web_components/blob/master/src/utils/upload.js) so we can overwrite the name of the upload.  For testing purposes right now I just copied the file Object and changed it.
IE: 
![image](https://user-images.githubusercontent.com/61746913/78047529-753c1c00-7346-11ea-8f21-e942cf4a2809.png)


I know you mentioned another way of changing the file after the upload.  I would like to if possible change it before it actually gets placed on the server instead of afterwards. (Not sure on the details of large video files getting interrupted).

**Comment by subdavis** [comment]
@BryonLewis would https://github.com/girder/girder_web_components/pull/248 do what you want?

**Comment by BryonLewis** [comment]
perfect, I'll pull and test it out later.

**Comment by subdavis** [comment]
@BryonLewis I believe this is done.  Can we close this?
