### ISSUE TITLE
Show progress indicator during delete

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#26]
For large delete operations, it can take several seconds.  Need a progress indicator.

**Comment by BryonLewis** [comment]
The current system for deletion takes a look at what is selected on the page.  Both the folders and items that are selected and does a single rest request to delete all those items.  It then refreshes the page after all deletions are complete.
There are a couple of different ways this could be accomplished.  I would lean towards batching the requests into groups so that there is some granularity to when the display updates.

Create a 'deleting...' animation indeterminate progress bar on each item that is being deleted. 
Easy to do, but it is only removed once all items are deleted.

Use multiple requests for batching.  Batch multiple items together and then each folder would have it's own request for deletion.  Then you can update and refresh the display each time a folder, or group of items are finished deleting.  This would also use some sort of 'deleting' indicator to show that a folder/item is in the progress of being deleted.  Ideally I would like to be able to reach into the individual display of the row item and remove it after it is complete instead of relying on the girder web components refresh method.

Pinging the server to request the current data.  Setting up a standard internal to refresh the current data will remove items as they are deleted.  This has the benefit of being automatic but is inefficient and looks ugly because the indicator for refreshing will occur frequently.

**Comment by subdavis** [comment]
resolved in #215 actually.
