### ISSUE TITLE
Wrap breadcrumb instead of action buttons

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#27]
Change how the data browser's widget area wraps.

![image](https://user-images.githubusercontent.com/4214172/78400581-fe608680-75c4-11ea-93d0-1dbf643aa10b.png)

**Comment by BryonLewis** [comment]
I would think there are two different options for dealing with this.
1.  Editing the FileManager.vue component directly in Girde Web Components to implement a true row/column system for the items and prevent the overflow from pushing the columns to a new line.  We probably don't want to modify Girder Web Components though because of the overhead associated with doing that for this.
2.  We change the row containing the folder name and buttons to have a `flex-wrap: nowrap` set so that the longer folder names automatically wrap.  Trying to find a more specific selector but it looks like `.girder-data-table.girder-file-browser .row` is the most specific I can find. Reminder:  You can't use a scoped CSS attribute for a file if you plan on affecting children which would be the case in this method.

![image](https://user-images.githubusercontent.com/61746913/79119676-ef18d000-7d5e-11ea-8ccb-68fdc24fe030.png)
![image](https://user-images.githubusercontent.com/61746913/79119711-0657bd80-7d5f-11ea-8901-3b85eb26edde.png)

**Comment by BryonLewis** [comment]
Looking at it, it's probably better to suggest an upstream change in girder web components to prevent the items after the breadcrumb from wrapping instead of reaching in with the CSS style.
