### ISSUE TITLE
Left clicking off a track on background should de-select track

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#28]
When a region not inside the track box or near the track classification text right of the box is selected, it would be ideal to de-select the currently selected track

**Comment by subdavis** [comment]
Also see discussion on #12

**Comment by BryonLewis** [comment]
I took a quick look at this and it appears as though geoJS doesn't have a way to bind directly to the mouseEvent that a click isn't on any feature.
Looking at the geoJS documentation the easiest alternative I could find would be to bind a regular mouseClick to the `geo.event.mouseclick` instead of `geo.event.feature.mouseclick`.  You could then use the geo coordinates return with `polygonFeature.pointSearch(coordinates)` to see how many items are under the current mouse position.  If no items are found, tell the viewer parent to deselect.  If items are found take the top in the array.

I tried seeing there was a built in function in geoJS to do this but couldn't find anything. Let me know if anyone knows of a better alternative to do this?

**Comment by subdavis** [comment]
From #12 

> This may have a logical conflict with head/tail annotation since head or tail can be outside the bounding box and you wouldn't want to deselct in that case.
> It's possible that during head-tail annotation if you miss the annotation toggle, you could accidentally de-select your target frequently, so this may or may not be ideal.

To add to that, why would you want to de-select a track?  There isn't a user action in this app that requires no track to be selected, so being able to de-select a track like this, as far as I can tell, doesn't provide value to the user.

**Comment by BryonLewis** [comment]
> From #12
> 
> > This may have a logical conflict with head/tail annotation since head or tail can be outside the bounding box and you wouldn't want to deselct in that case.
> > It's possible that during head-tail annotation if you miss the annotation toggle, you could accidentally de-select your target frequently, so this may or may not be ideal.
> 
I could very well be misinterpreting this.  There is already a check in `annotationClick `to make sure you don't deselect or select another track while `featurePointing` is active.  The current deselect action is clicking on the item again.  So clicking inside the box if you miss the toggle would deselect.

> To add to that, why would you want to de-select a track? There isn't a user action in this app that requires no track to be selected, so being able to de-select a track like this, as far as I can tell, doesn't provide value to the user.  

There is a sort of mental catharsis to being able to deselect a current component even if there is no reason.  Just knowing that you have the control to deselect by clicking blank space.  It's fairly common in most apps that have you select and edit objects:  Powerpoint, Google Drawing, QtCreator, Unity3d.  I think it's an expected behavior.  It's how I thought it worked until I learned that clicking on the same annotation de-selects.

**Comment by mattdawkins** [comment]
For me anyways I was making slides and didn't want 1 fish highlighted in a different color (my selection)

Also in the desktop GUI its ingrained in people mind as after resizing the box it "saves" the edits

**Comment by BryonLewis** [comment]
I have an idea to add this in,  I just need to double check and confirm that it doesn't negatively impact head/tail features.
