### ISSUE TITLE
[BUG] Mismatch between local alias and published `vue-media-annotator`

### ISSUE THREAD

**Issue by AlmightyYakob** [VIAME/VIAME-Web#304]
**Describe the bug**
When importing some components from the published `vue-media-annotator` npm package, they attempt to reference other components in the package. However, they're not actually importing from the published package, but from the alias defined in `jsconfig.json`. This alias resolves to `src/`, which means that in Viame-Web, the following example import succeeds no problem:

https://github.com/VIAME/VIAME-Web/blob/7cc58fe54b4398fa3dc45b0b396ec4a6a81350dd/client/src/components/LayerManager.vue#L12

Doing this import when using the published package, this import path is taken literally, which means it looks for `components` in the root package directory. This import fails, as the proper path is `src/components`.

**To Reproduce**
1. In an external application, add the `vue-media-annotator` package to your project.
2. Attempt the following import
3. There should be errors in the console when building/serving.

**Expected behavior**
The import succeeds.

---

I think ideally the publish package would be rooted at the `src` directory, as I don't think anything above that directory is needed? However I'm not sure if configuring the npm package that was is feasible/possible.

**Comment by subdavis** [comment]
There are a couple solutions to this issue

1. use only relative imports in the vue-media-annotator package.  This is how GWC does it.
2. temporary fix: set the `vue-media-annotator` base alias in `vue.config.js` and `tsconfig.json`. 
3. largest effort: switch build process to create an ESNext module.  This is tricky because we don't want to bundle vuetify, vue, and other third party dependencies.  It also means we'd have to switch to rollup.  I'd like to do this eventually, but not until `vue/vite` gets a stable release.

Let's try 2 first, then 1, and 3 at some point in the future.  @AlmightyYakob does that work for you?

**Comment by AlmightyYakob** [comment]
> Let's try 2 first, then 1, and 3 at some point in the future. @AlmightyYakob does that work for you?

Option 2 would be something done directly in the other project, correct? I'm good with this plan regardless, just making sure I understand. I've already set aliases in the other project to fix this for the time being.

**Comment by subdavis** [comment]
Yep.

> . I've already set aliases in the other project to fix this for the time being.

So that solution is working for you in the short term?

**Comment by AlmightyYakob** [comment]
> Yep.

Sounds good.

> So that solution is working for you in the short term?

Yes, I don't seem to have any further import errors, at least that I've witnessed.
