### ISSUE TITLE
Document basic interactions and link the document from the application

### ISSUE THREAD

**Issue by aashish24** [VIAME/VIAME-Web#31]

**Comment by subdavis** [comment]
@aashish24 or @mattdawkins please review the docs at https://github.com/VIAME/VIAME-Web/wiki/User-Documentation

When we've approved them, I'll open a PR to link these from inside the application.

**Comment by aashish24** [comment]
this looks like a great step forward @subdavis few suggestions: 

1. Is it possible add a screencapture clip for the section in which we discussed UI

2. The light gray color background is hard to see on my screen. Is it possible to change it? or make it darker?

**Comment by subdavis** [comment]
> Is it possible add a screencapture clip for the section in which we discussed UI

Because of the keyboard interaction, screen clips won't be that useful.  Things will happen in the clip, and the person watching won't know what I did to make it happen.  We would need some post-production to overlay stuff like "Press F" on the video.

Screen clips also have a much higher maintenance cost, because if we remove a button, we have to redo a lot of work.  I expect many of the controls to change dramatically over the next month.

This isn't to say we can't do clips, just that I don't know if it's a good investment yet.

> The light gray color background is hard to see on my screen. Is it possible to change it? or make it darker?

I don't think I understand.  Is this a contrast problem?  How is this related to documentation?

**Comment by aashish24** [comment]
yeah documentation with clips is higher maintenance. @mattdawkins is the expectation is that we will have documentation with clips or just pure text based documentation is fine for now?

@subdavis for example in the documentation example below (q) has lighter gray background to highlight but it is not clearly visible on the screen but looking more into it, markdown does not support colors so the rendering is done outside of if, so I guess we cannot change it unless we do something extra or change the documentation system. 

Also, just for reference, look at the documentation here created by Seb: https://www.hydroframe.org/sand-tank-user-manual something we could do in the future perhaps for docs with UI clips.

**Comment by mattdawkins** [comment]
Anything would be fine as a first pass and a step up from nothing. If difficult getting images in now in first pass then just text fine and later on adding images.

**Comment by subdavis** [comment]
![Screenshot from 2020-04-09 11-31-30](https://user-images.githubusercontent.com/4214172/79481972-2ea11f80-7fde-11ea-8c1a-20b84bcffcf5.png)

Here's how it will look initially.

**Comment by subdavis** [comment]
Merged to master.
