### ISSUE TITLE
[BUG] Do not resize bounding box when drawing a head tail loc for detection with existing box

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#357]

**Comment by mattdawkins** [comment]
One secondary exception could be if one of the head/tail location is outside of the box but the line still intercepts, would want to expand box to cover new point (with no added gap)

If the head tail line location does not intersect with the box at all, then the box should be remade

**Comment by subdavis** [comment]
After staring at this problem for a while,  I don't really know what to do about it.

The issue here is that this system currently makes no distinction between a bounding box that a user made and one that a recipe or other automated process came up with.

This would actually be a significant change affecting client and server, and I don't think it makes sense to do all that to support this.

I'm going to disable padding completely now.  The issue here is that, without padding, much of the complexity in recipes can be gutted (unused).  I don't want to get rid of it, but I don't like keeping overly complex code that doesn't have a purpose.

![Screenshot from 2020-10-21 15-01-17](https://user-images.githubusercontent.com/4214172/96770452-71d5b400-13ae-11eb-8430-212aff116bae.png)
