### ISSUE TITLE
Make it more clear which track is highlighted in the list when selecting a track

### ISSUE THREAD

**Issue by aashish24** [VIAME/VIAME-Web#37]

**Comment by BryonLewis** [comment]
The current system as of now has the track listing highlight in the accent color and scroll directly to the proper track.  
![image](https://user-images.githubusercontent.com/61746913/79146216-02905f00-7d90-11ea-9fba-6e697652f99f.png)

I'm awaiting word back from the UI/UX team about additional changes.  I think that some of the track editing like the type selection and the additional '...' menu should be placed somewhere else to clean up the track list area.  Another thing is possibly just indicating selection with a border instead of a full highlight.
![image](https://user-images.githubusercontent.com/61746913/79146330-3f5c5600-7d90-11ea-9a2b-2f3113d6bfc2.png)
