### ISSUE TITLE
[BUG] If making a new detection using a line and holding down left click it draws a spline/other

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#370]
**Describe the bug**
If making a new detection using a line and holding down left click it draws a spline, but left clicking twice for head tail spots works pretty good

**To Reproduce**
1. Any dataset, go into line edit mode, draw a new line holding it down gets into a confusing state where user has to terminate via right clicking

**Comment by BryonLewis** [comment]
@subdavis  - do you know of clean way we could provide access to the 'annotator' within recipes to change settings?
Or perhaps allow the recipe to pass some settings down to the annotator/Layers.  There is a built in setting in the `annotator.map.interactor` settings that allows for turning on/off continuous point creation.  I believe you can even support specific distances between points.

Now I could just make it so that line mode doesn't allow drawing sequential points, but I don't know if that is sustainable across all lines and possible future lines.

**Comment by subdavis** [comment]
> setting that allows for turning on/off continuous point creation

I vote we turn it off completely for now.   Free-handing polygons isn't supported properly, it's more of an accident than a feature.  I understand that a brush feature is needed, but that would be a separate input mode, IMO.  

I'd rather not have a feature at all then have something that 30% works.  We should have a proper use case before we commit to supporting something as potentially complex as freehand drawing.  There's a huge backlog of features and bugs on this tool.  I don't see a good argument for adding code complexity to support this.  at this time, but that's just me.

**Comment by BryonLewis** [comment]
Good point.  I'll just make a note of the option here so it can be pushed into a future PR:

The options aren't documented in geoJS so I'm putting a reference here.  I was mistaken in that these are AnnotationLayer Options.  So they should just apply inside of the editAnnotationLayer
https://github.com/OpenGeoscience/geojs/blob/master/src/annotationLayer.js#L127-L139

```
m_options = $.extend(true, {}, {
    dblClickTime: 300,
    adjacentPointProximity: 5,  // in pixels, 0 is exact
    // in pixels; set to continuousPointProximity to false to disable
    // continuous drawing modes.
    continuousPointProximity: 5,
    // in radians, minimum angle between continuous points to interpret them as
    // being coliner
    continuousPointColinearity: 1.0 * Math.PI / 180,
    finalPointProximity: 10,  // in pixels, 0 is exact
    showLabels: true,
    clickToEdit: false
}, arg);
```
Note: that I believe this has a nasty side effect in that the point is only created on mouse release within the map interactors click distance.  So clicking and holding down just results in nothing instead of a single point, followed my other points as you release.  Doesn't entirely feel natural.

**Comment by subdavis** [comment]
FWIW, we can do what a lot of draw tools do and drop the line resolution after shape creation.  We wouldn't necessarily have to do something like while the draw is happening.
