### ISSUE TITLE
[BUG] [Regression] Docker Hub Worker failing to build

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#405]
**Describe the bug**

"No space left on device"

I assume we're running into some kind of upper limit on disk usage 

https://hub.docker.com/repository/registry-1.docker.io/kitware/viame-worker/builds/2c7af7ad-e569-417e-b6dd-d6ef96df4bf0

I wonder if there's some kind of 10GB limit we broke through.

**Comment by AlmightyYakob** [comment]
One of the main ways forward we discussed was to not package the models into the VIAME-Web image, and set up a procedure for fetching these models from data.kitware.com. There are a few ways we could store these:

* On Girder - The good thing here would be users could download these models directly from Girder if they wanted to. However, it may prove to be vastly inefficient when it comes to running pipelines / transferring these large data files. @subdavis I believe you had input here?
* In a docker volume - This would be more akin to what we currently have. I'm not sure what would be required from VIAME itself so that it can access these models.

**Comment by subdavis** [comment]
I think the trouble with girder is that viame would need direct filesystem access to these model files, and I definitely don't want the worker to be downloading models from girder to run.

If they could be in a read-only collection sort of like the training data and share a docker volume with the worker such that they're exposed through girder but not managed by girder, that could work.  

I think I'd like for the `VIAME` base image to be responsible for populating these models through a script, since some folks use the viame base image directly.

So if there were an automated script in the base image at `/usr/bin/downloadmodels.sh` (For example) then this could be part of the entrypoint of the base image, and we could call this script from the worker at container startup. We could then have a new volume for models, and the script could see if the models are missing and pull them.  That way model updates happen automatically on deployment day.

What do you think about something like that?

**Comment by subdavis** [comment]
## Another option: `--volumes-from`

This would require less "new" engineering:  Just break the models into their own container.  It could be a `FROM scratch` [scratch](https://hub.docker.com/_/scratch) base image with the models at `/data/models` or whatever.  Build that, push it to docker hub.

Then, when you want to run viame, you have to `docker run --volumes-from viame/models:ro viame`

I think this option is my preference, unless there are cons I'm not seeing.
