### ISSUE TITLE
[BUG] When navigation guard dialog for save is open, pressing `escape` causes confirm behavior

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#409]
When you forget to save and try to navigate away, if you press escape, this should be a `cancel` operation and not a `confirm` operation.

The effect is that `escape` makes you lose your changes when you probably wanted to abort the navigation.

**Comment by BryonLewis** [comment]
Below is just for my own notes:

This is specifically on the Vue-Router navigation guard and I'm assuming because we don't do a cancel on navigation.  Meaning you choose either 'Discard' or 'Save' and then it routes to the new page, there is no blocking of the navigation.  This is my mistake and I don't understand why I didn't make it behave like the reload/switch url guard where cancel prevents the action.  I can change 'Discard' to 'Cancel' and prevent the navigation if the user clicks on cancel.
