### ISSUE TITLE
[BUG] Video doesn't load on slow network.

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#447]
![Screenshot from 2020-11-17 12-58-59](https://user-images.githubusercontent.com/4214172/99428455-aae14580-28d4-11eb-888a-4dcd5e7ef124.png)

**Describe the bug**

Video doesn't load properly on slow networks.

**To Reproduce**
1. load the data browers.
2. open inspect, enable Fast 3G network speed throttling.
3. Open a video
4. see detections load, but video first frame doesn't show up.

**Related data**

**Expected behavior**
Video should load.

**Desktop (please complete the following information):**
 - OS: Linux ubuntu
 - Browser chrome

**Additional context**

**Comment by subdavis** [comment]
Spent a couple hours on this trying to reproduce in geojs using the hidden quads example.  Couldn't get a video to show up at all using that example.  Don't have any more time to spend on it right now.

**Comment by BryonLewis** [comment]
I just brought it up and attempted on a video, looks like it is the first frame, because advancing a frame at a time it works.  The first frame is loaded differently and I'll look into this right now.  My immediate guess is that we usually load the layer then display the frame and the timing typically works out that the the first frame is ready before loaded.  I'm guessing that the layer needs a kick if the frame loads far after the layer.

**Comment by subdavis** [comment]
GeoJS sets up listeners to do the timing on its own.  If you pass it a URL string instead of a video element, it will even construct a video container.

I think this is a GeoJS bug, but I can't figure out how to get a basic quad layer working.

**Comment by BryonLewis** [comment]
You can play with this: [Basic Example, click to play video](https://opengeoscience.github.io/geojs/tutorials/editor3/?src3=ZVNNj5swEL3zK6ZqJYiUdSAfJGGVU9Wqh-1t1ctqDw4MibUGp7ZJSiP-e8c22aaqBJLH8.Fm3hufuYaGn2AHB1SMTsk1AmhVhQXEH8mOp2TPZmAs1xZKbC1qrKBFSvzMpaiVbgWnmOAq4PqrgIcsW02hL2CRDy7.t1JNAXk0TB4jqnWSvETgsOcGwQqJIHmPGlQL9oiun4h-VmrkFp-cK4mVaWLKPhNsCN7BfzE1nTuN8RTcEKNlCniJf3a8YmdRoYpfb12EVGrDOW.RHsBdGALwQCPE1-BPfKk4VDBofcMVtxysolJGtAcah6jQfeTLMOdMXq6BRRddEmOoDVyISKiQSGtES5Tu--B2cIrIqL3pm6bkTt6onW9Zms8Dv8s5yxbLfLNc5elmu1rNPd3yXYY0ZdvFOsRS3mK5WWb5IkvXm2y9XQ83bU9Yirqn.jstgRT9iwxGdbpEivMmLQVjM.rcVDPaAXukKd.QPHg3u-C-iaPhlfgZp9f8kpD1KQnbNGGqTeJSivKN2Y7mFFySXnXXllaQ.skERqoOI7nfnr8.wQ.fyxeJDVF7o6YW2lhIeFvR5sh-4nVznZKEofldkDIon6TUB4CoIfngLwLUuy4hRZg2tiAVr0iSHu2UGIBK0ZOwRxLXJ2ikVWhdsWGUVR2c7LTX.ezEO4MjTiDF31R3aFxeeG8IRJ3-0XgkmXnHDqzu8PHu2pVP.AwDoKSnc713OpDR6zb8Dw__)
I notice this one doesn't play the first frame either mostly because I think it is being created by geoJS.
So this is more our setup and it does replicate the issue, ignore the chromecast video.  I needed something besides bigBuckBunny which has  black first frame.  [Example](https://opengeoscience.github.io/geojs/tutorials/editor3/?src3=ZVNNb9swDL3nV3DYADlAKuf7w0UuG1bs0N2GXYodVJtxhcqSJ8npvCD.fZRkdx12MGCKpN4j39NZWGhEC0eo0XD6yy4TAG0qLIC9p5jNKM5zcF5YDyVqjxYr0EiNn4SSJ2O1FFSTUgVcfhVws1hsZtAXsNpeQ.9vY5oCtpPr9HZCd7VKlAgCHoVD8FIhKNGjBaPBP2HgM6GPlxaFx.uQyphxDaPuM8Gm4iP8V3Oi.84im0EYYohcAQ.sZycqfpYVGvZjZJFaiUZIjtWT0mjnIZYSRGXKrqHBBpzPCkOUsXRV4BN-eGtRGbrkCEx03rDx3NkSjuzJ-7bI89I0jdGV8MJ5Y0WNvDamViha6Tgl89qfb2Kfu3nsymf0uRNNqzC.M.ajrGu0d53mTbum--MiAnFHoHEhA8W7NEcWR2ZpUoc-LjZggzc0spOakIFmsf0kXsNDMnu4JLVDdUnKonXwQoJDhSRuIzVJ.9indIAzJNophpE4NXdqtMDywOfbZfLBeskXq.V2v95s5.vDZrOMtlCvdpnP-WG1S7XUt1rv14vtajHf7Re7w-46erDFUp564t9ZBeS8v8jgTGdLpLoYFgOf6w.awDCfFS8ZRR-y5OspNzpjpZLlM.ckmpVCkXNOnS69JCdmUxiWUQ.r-.Lt6z18j2iDEcbhT9KSaTKhK.Kw6qdRmcCFRBqtlFjEKJsTDwB5guxdPEhQr5tPLdJp5iH4ipbeo5.RjGRIepz-ieSLDRZJbB0uuw7CmToISy-sz1vRORxwBp-Gk-oNmlAvoncEYtp.VBzWyGPiCN52ePvmOFyfxRmugIoe8eVtMoAM2fDW.gA_)


Temp fix would be to seek right after the initial drawing.  Will fix the non display of the first frame.  Only difference I can find is in the [HTMLMediaElement.played](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) value stating the browser has played one frame when it is unlocked vs when it is 3G fast

**Comment by subdavis** [comment]
Should we put a `this.video.seek(0)` after the initial drawing in `VideoAnnotator.vue` @BryonLewis ?  Seems pretty harmless to me, as long as we add a comment about why.

**Comment by BryonLewis** [comment]
yeah, I can't imagine it hurting.  Just make sure it is either calling `this.seek(0)` or `this.video.currentTime = 0`.  I'd lean more to using `this.seek(0)`, just so we ensure annotations and everything else are synced (they should be anyways with everything initialized to 0) It just feels better to have only one spot to interface with `this.video.currentTime`.
