### ISSUE TITLE
[FEATURE] Implement windows platform features for VIAME Dive

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#466]
Implement and test on windows. 

* Pipeline running.
* Load/save of data

**Comment by BryonLewis** [comment]
I have a branch that I made just doing some testing to see how it works.  I tested it with running pipelines on CPU and GPU as well.
Some notes below about what I did:

- Added a simple test system for windows, else the platform defaults to linux, this can be improved in future
- I needed to move the `nvidia-smi` checking code into platform dependent areas for linux/windows.  I'm using the most common location for `nvidia-smi` since it is rarely added to the PATH on windows.
- Default VIAME install is `C:\Program Files\VIAME` but not everyone uses their C: drive for programs.  So added some code to test for the `%PROGRAMFILES%` variable and update the `defaultSettings` viame location if necessary.
- I check to make sure kwiver.exe is running as well in the beginning so it takes a few seconds.  We may want to add an in progress loader/spinner to the kwiver checking.
- I added an open folder to the VIAME Path location.  Typing window paths isn't really fun so it just felt more natural to navigate if needed.  I need to update the styling and size of it though.
- Running jobs behave similar (with same output files and run log) except for the jobs panel output.  I need to look into redirecting and displaying to stdout at the same time in windows.

I have a branch and it has done most of the work of getting kwiver and the setup batch files to work together.
`client/desktop-windows` - branch that has working kwiver/gpu checking in windows as well as running pipelines.

**Comment by subdavis** [comment]
Sounds great, open a PR!

**Comment by BryonLewis** [comment]
I have some other items I want to test/fix before a PR.  I'm going to use this issue as a log to help organize stuff (warning you if you want to unsubscribe, so you don't get continuous warnings.)

Need to figure out what is going on between GPU and CPU versions.  Same executable with the same source file running the the `generic_object_proposal`s pipeline on two different machines with different versions of VIAME (CPU only, vs GPU version) behaves differently.

- The CPU only on laptop takes like 5 minutes on the source data and provides relevant results.
- The GPU version of VIAME on a more powerful desktop started and ran for 20+ minutes (stopped before allowing it to continue).

Testing parameters to determine the problem:
- Get the command from the log manually and run it.  I want to make sure it isn't something in the way the command was built.
- Install the CPU only version on the desktop and run it to determine if it is an issue with how the GPU one is configured or setup.

List of other TODOs before creating PR:

- [ ] Ensure the %PROGRAMFILES% code works properly, and that executes before the confirmation of Kwiver install
- [ ] Add in a loading spinner or something to the testing of the kwiver install and GPU.  They take long enough (2-4 seconds) that we need an indication that something is attempting to verify when the user clicks save or navigates to the page.
- [ ] At least look into application signing (low priority).  Windows continually gives the "WARNING THIS SOFTWARE IS UNVERIFIED" stuff when running the electron version for the first time.
- [ ] Check symlinks and how they behave when using shortcuts for the data
- [ ] On windows nvidia-smi.exe isn't global and could be in a different location depending on where they install their drivers.  May want to give a clarification that just because a GPU couldn't be found doesn't mean that it won't work.
- [ ] Text log for the jobs panel.  Need to look into getting it to both write to the runlog.txt and the jobs display at the same time.  Right now I have it only writing to the runlog.txt file.

**Comment by subdavis** [comment]
You could always open a draft.   I promise not to harass you until you ask for a review.
