### ISSUE TITLE
[BUG] Changing track type during creation causes weird glitch.

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#475]
**To Reproduce**
1. Start creating a new track via rectangle
2. While in creation mode, change the track type
3. Try to finish drawing the box.

**Comment by BryonLewis** [comment]
Doing some additional testing it looks like the more specific instance is if you change the type but don't submit it by clicking enter, or selecting another one from the list.

When you swap focus from the input box element to the geoJS area it immediately deselects your current track without doing creation.  Need a way when focus is enabled on an input element that requires off-clicking to complete it's change that it won't trigger a select null or select another track while technically still in editing mode.

GeoJS turns off the creation mode immediately when clicking but doesn't realize that at the same time the other layers are decided to deselect the track because it things you are clicking off of the track and that is what causes the issue.
