### ISSUE TITLE
Upload progress reporting is insufficient.

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#5]
The upload progress controls need some attention.  All you get is an indeterminate progress bar and a label that says `0 images` the whole time an upload is happening.

There's nothing to indicate to the user if things are still happening or the UI has gotten stuck, particularly if the upload is large.

I'd consider this of moderate priority.

**Comment by BryonLewis** [comment]
Updates that are completed:

- Switch to utilizing the girder_web_component/mixin utils for the upload (thanks for the info Brandon)
- Updated the progress dialog to count down the completed number of image files.  (there is a delay as the first ones start uploading)
- Fixed it so sequential pending uploads operate properly
- Edited the display so that Videos will display the video size and then count down the remaining filesize for the upload.
- Updated the upload process so that it will handle adding additional uploads while in the process of uploading items.
- Changed the button from ‘Upload’ to ‘Start Upload’ on numerous instances I believe that clicking on ‘Upload’ would allow me to add more files.

Stuff left to do

- Implement some proper error handling, using Girder Web Components as a base
- Handle weird case of uploading multiple video and csv files.
- If there are multiple video files we should indicate total number and size of all of them
- If there is a single video file we use that as the size basis for the calculation and progress
- General self review of code changes to make sure all items make sense and are clear and efficient.
