### ISSUE TITLE
Add distinction between exporting filtered and unfiltered tracks

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#66]

**Comment by subdavis** [comment]
* What sort of edit/save operations would a user perform on a filtered track?
* What sort of distinction should the user see, and when should the see it?
* What is the general purpose of this feature -- what sort of high-level task might a user be engaged with where saving filtered vs unfiltered tracks is important to them?

**Comment by subdavis** [comment]
Followed up with Matt:

* I misunderstood this.  Matt wants to be able to **export** distinguishing filtered and unfiltered.  Filtering is ephemeral, so it only makes sense to do this from within the viewer itself (server doesn't know what the filter is: it has to be told)
* Each confidence pair pertains to an entire track.  We should bubble this state up onto the track object, because it's wasted to duplicate across all detections.
* We should filter tracks below the confidence thresh out of the track list.
* Might make sense to persist the thresh for each video on the server as metadata, low priority, no action for now.
